name: Update Dependencies

on:
  push:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  UpdateDependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.9

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install poetry export plugin
        run: |
          poetry self add poetry-plugin-export

      - name: Lock and export
        run: |
          poetry lock
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':arrow_up: 自动更新依赖文件'
          add: |
            'poetry.lock'
            'requirements.txt'